### ISSUE TITLE
Responce URL not found

### ISSUE THREAD

**Issue by tridev-it-solution** [dwivedianuj9118/phonepe-payment-gateway#4]
<?php
use Dwivedianuj9118\PhonePePaymentGateway\PhonePe;
require __DIR__ . '/vendor/autoload.php';

$config = new PhonePe('PGTESTPAYUAT','099eb0cd-02cf-4e2a-8aca-3e6c6aff0399',1);//merchantId,SaltKey,SaltIndex after onboarding PhonePe Payment gateway you will got this.
$merchantTransactionId='MUID' . substr(uniqid(), -6);// Uqique Randoe transcation Id
$merchantOrderId='Order'.mt_rand(1000,99999);// orderId
$amount=100;// Amount in Paisa or amount*100
$redirectUrl="http://localhost/phonpe/success.php";// Redirect Url after Payment success or fail
$mode="UAT"; // MODE or PAYMENT UAT(test) or PRODUCTION(production)
$callbackUrl="http://localhost/phonpe/success.php";//Callback Url after Payment success or fail get response
$mobileNumber=9876543210;//Mobile No
$data=$config->PaymentCall("$merchantTransactionId","$merchantOrderId","$amount","$redirectUrl","$callbackUrl","$mobileNumber","$mode");// call function to get response form phonepe like url,msg,status
//header('Location:'. $data['url']);//use when you directly want to redirect to phonepe gateway
//echo $data['url']; // here you get url after initiated PhonePe gateway

print_r($data);
?>

RESPONCE :::::::
base= eyJtZXJjaGFudElkIjoiUEdURVNUUEFZVUFUIiwibWVyY2hhbnRUcmFuc2FjdGlvbklkIjoiTVVJRDI4OWIyNCIsIm1lcmNoYW50VXNlcklkIjoiT3JkZXI5ODUyMCIsImFtb3VudCI6IjEwMCIsInJlZGlyZWN0VXJsIjoiaHR0cDpcL1wvbG9jYWxob3N0XC9waG9ucGVcL3N1Y2Nlc3MucGhwIiwicmVkaXJlY3RNb2RlIjoiUE9TVCIsImNhbGxiYWNrVXJsIjoiaHR0cDpcL1wvbG9jYWxob3N0XC9waG9ucGVcL3N1Y2Nlc3MucGhwIiwibW9iaWxlTnVtYmVyIjoiOTg3NjU0MzIxMCIsInBheW1lbnRJbnN0cnVtZW50Ijp7InR5cGUiOiJQQVlfUEFHRSJ9fQ==\n result= 88123959f40d386e3add8e06a53a7fec2c3145e905cd3c8f6abc971172998cf3###1Array ( [responseCode] => 200 [url] => [msg] => [status] => )

I can't find any URL or message in array

**Comment by dwivedianuj9118** [comment]
I have update repo please check this issue occur due to phonepe server issue so now I have display the message what the issue in phonepe server
